name: Upload to COS
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build Astro project
        run: pnpm run build

      - name: Install COSCLI
        run: |
          wget https://github.com/tencentyun/coscli/releases/download/v0.11.0-beta/coscli-linux
          chmod +x coscli-linux
          sudo mv coscli-linux /usr/local/bin/coscli

      - name: Configure COSCLI
        env:
          SECRET_ID: ${{ secrets.SECRETID }}
          SECRET_KEY: ${{ secrets.SECRETKEY }}
          BUCKET: ${{ secrets.BUCKET }}
          REGION: ${{ secrets.REGION }}
        run: |
          coscli config add \
            -a mybucket \
            -b $BUCKET \
            -r $REGION \
            -i $SECRET_ID \
            -k $SECRET_KEY

      - name: Sync to COS (with multi-threading)
        run: |
          coscli sync ./dist/ cos://mybucket/ \
            --include "*" \
            --exclude ".git/*" \
            --part-size 10 \
            --thread-num 30 \
            --rate-limiting 0 \
            --recursive

      - name: Clean up old files (delete remote files not in local)
        run: |
          # List remote files and delete those not in local dist
          coscli ls cos://mybucket/ --recursive > remote_files.txt
          find ./dist -type f | sed "s|./dist/||" > local_files.txt

          # Find files that exist remotely but not locally
          comm -23 remote_files.txt local_files.txt > files_to_delete.txt

          # Delete those files
          while IFS= read -r file; do
            if [ -n "$file" ]; then
              echo "Deleting remote file: $file"
              coscli rm cos://mybucket/"$file"
            fi
          done < files_to_delete.txt