name: Upload to COS
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build Astro project
        run: pnpm run build

      - name: Install coscmd
        run: sudo pip install coscmd

      - name: Configure coscmd with optimized settings
        env:
          SECRET_ID: ${{ secrets.SECRETID }}
          SECRET_KEY: ${{ secrets.SECRETKEY }}
          BUCKET: ${{ secrets.BUCKET }}
          REGION: ${{ secrets.REGION }}
        run: |
          coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION -m 20 -p 10

      - name: Upload to COS with retry
        run: |
          # 设置重试机制
          max_retries=3
          retry_count=0
          until [ $retry_count -ge $max_retries ]
          do
            echo "尝试上传到COS (第 $((retry_count+1)) 次)"
            coscmd upload -r -f --delete ./dist/ / --ignore "./.git/*" && break
            retry_count=$((retry_count+1))
            echo "上传失败，等待10秒后重试..."
            sleep 10
          done

          if [ $retry_count -eq $max_retries ]; then
            echo "上传失败，已达到最大重试次数"
            exit 1
          fi

          echo "上传成功完成"
