name: Upload to COS
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build Astro project
        run: pnpm run build

      - name: Install coscmd
        run: sudo pip install -U coscmd

      - name: Configure coscmd
        env:
          SECRET_ID: ${{ secrets.SECRETID }}
          SECRET_KEY: ${{ secrets.SECRETKEY }}
          BUCKET: ${{ secrets.BUCKET }}
          REGION: ${{ secrets.REGION }}
        run: |
          coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION -m 30

      - name: Upload to COS
        env:
          BUCKET: ${{ secrets.BUCKET }}
        run: |
          coscmd -v upload \
            -r                # 递归上传目录
            -f                # 强制覆盖同名对象
            --delete          # 远端多余文件同步删除
            --ignore "./.git/*" \
            --force           # 非交互式确认
            --slice-size 5M   # 分块大小 5 MiB
            ./dist/           # 本地目录
            cos://$BUCKET/    # 目标 COS 路径
