name: Upload to COS
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # 增加超时时间到30分钟
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build Astro project
        run: pnpm run build

      - name: Install coscmd
        run: sudo pip install coscmd

      - name: Configure coscmd
        env:
          SECRET_ID: ${{ secrets.SECRETID }}
          SECRET_KEY: ${{ secrets.SECRETKEY }}
          BUCKET: ${{ secrets.BUCKET }}
          REGION: ${{ secrets.REGION }}
        run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION

      - name: Upload to COS with retry
        run: |
          coscmd upload -r -f --delete --sync-timeout 300 ./dist/ / --ignore "./.git/*" || {
            echo "First upload attempt failed, retrying..."
            sleep 10
            coscmd upload -r -f --delete --sync-timeout 300 ./dist/ / --ignore "./.git/*"
          }

      - name: Verify upload
        run: coscmd list /
